### ISSUE TITLE
CenterCrop

### ISSUE THREAD

**Issue by baochenfu** [Kay1794/Motion-Graph-Video-Prediction#1]
I notice centercrop is not being used. Is centercrop a must?
#DataLoader.py (L58-L59)

**Comment by Kay1794** [comment]
Thank you for your question. We use centercrop (defined in DataLoader.py L69-L75) to first crop a square out of the original frame and resize it to 512 X 512, which fits the input shape of the model.

**Comment by baochenfu** [comment]
The code in the dataloader is:

        crop_img = self.CenterCrop(**im**, side_len, side_len)
        final_img = cv2.resize(**im**, self.config['in_res']).copy()     
        imgs.append(final_img)
        return  imgs
   
It appears that the CenterCrop image was not used

**Comment by Kay1794** [comment]
> The code in the dataloader is:
> 
> ```
>     crop_img = self.CenterCrop(**im**, side_len, side_len)
>     final_img = cv2.resize(**im**, self.config['in_res']).copy()     
>     imgs.append(final_img)
>     return  imgs
> ```
> 
> It appears that the CenterCrop image was not used

I see. In the the original model was trained without CenterCrop. So it is not a must. The code is fixed now. Thank you for pointing it out!
